import LanguageSetup from '@/components/LanguageSetup';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js'
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <LanguageSetup>{children}</LanguageSetup>
      </body>
    </html>
  );
}
